<a href="https://colab.research.google.com/github/gudellijagan001/jagan01/blob/main/assi_1_part_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
list=[1,2,3,4,4,5,6]
print(list)

[1, 2, 3, 4, 4, 5, 6]


In [2]:
List = [1, 2, 4, 4, 3, 3, 3, 6, 5]
print("\nList with the use of Numbers: ")
print(List)
List = [1, 2, 'Geeks', 4, 'For', 6, 'Geeks']
print("\nList with the use of Mixed Values: ")
print(List)


List with the use of Numbers: 
[1, 2, 4, 4, 3, 3, 3, 6, 5]

List with the use of Mixed Values: 
[1, 2, 'Geeks', 4, 'For', 6, 'Geeks']


In [3]:
import numpy as np
arr1=np.array([1,2,3,4,5])
arr2=np.array([1,3,2,4,5])
arr3=arr1+arr2
arr4=arr1*arr3
arr5=arr1-arr4
arr6=arr3/arr4
print("the product of array is",arr4)
print("the multiplication of array is",arr3)
print("the substration of array is",arr5)
print("the divide of array is",arr6)

the product of array is [ 2 10 15 32 50]
the multiplication of array is [ 2  5  5  8 10]
the substration of array is [ -1  -8 -12 -28 -45]
the divide of array is [1.         0.5        0.33333333 0.25       0.2       ]


In [4]:
#using numpy creationof sine,log and exponential of two arrays
import numpy as np
arr1=np.array([10,20,30,40,50])
arr2=np.array([12,3,5,4,2])
arr3=np.sin(arr1)
arr4=np.cos(arr2)
arr5=np.tan(arr2)
arr6=np.log(arr1)
arr7=np.exp(arr1)
arr8=np.log2(arr2)
print(arr3)
print(arr4)
print(arr5)
print(arr6)
print(arr7)
print(arr8)

[-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]
[ 0.84385396 -0.9899925   0.28366219 -0.65364362 -0.41614684]
[-0.63585993 -0.14254654 -3.38051501  1.15782128 -2.18503986]
[2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]
[2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17
 5.18470553e+21]
[3.5849625  1.5849625  2.32192809 2.         1.        ]
